const express = require('express');
const router = express.Router();
const bannerRoutes = require('./bannerRoutes');
const categoryRoutes = require('./categoryRoutes');
const productRoutes = require('./productRoutes');
const userRoutes = require('./userRoutes');
const configRoutes = require('./configRoutes');
const contactRoutes = require('./contactRoutes');
const postRoutes = require('./postRoutes');
const menuRoutes = require('./menuRoutes');
const certificateRoutes = require('./certificateRoutes');
const partnerRoutes = require('./partnerRoutes');
const estimateRoutes = require('./estimateRoutes');
const chatRoutes = require('./chatRoutes'); 

router.use('/certificates', certificateRoutes);
router.use('/partners', partnerRoutes);
router.use('/estimates', estimateRoutes);
router.use('/chat', chatRoutes);
router.use(bannerRoutes);
router.use(categoryRoutes);
router.use(productRoutes);
router.use(userRoutes);
router.use(configRoutes);
router.use(contactRoutes);
router.use(postRoutes);
router.use(menuRoutes); 
module.exports = router;