const express = require('express');
const router = express.Router();
const bannerRoutes = require('./bannerRoutes');
const categoryRoutes = require('./categoryRoutes');
const productRoutes = require('./productRoutes');
const userRoutes = require('./userRoutes');
const orderRoutes = require('./orderRoutes');
const contactRoutes = require('./contactRoutes');
const postRoutes = require('./postRoutes');
const menuRoutes = require('./menuRoutes');
router.use(bannerRoutes);
router.use(categoryRoutes);
router.use(productRoutes);
router.use(userRoutes);
router.use(orderRoutes);
router.use(contactRoutes);
router.use(postRoutes);
router.use(menuRoutes);
module.exports = router;